apiVersion: v1
kind: Service
metadata:
  name: youtube-playlist-api
spec:
  selector:
    app: youtube-playlist-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
